Add module for import BRD MT940bank statements.
OCA/l10n-romania pull request #10
Opened 2016-06-21 06:54 UTC by feketemihai

2016-06-21 07:03 UTC, pedrobaeza commented on account_bank_statement_import_mt940_ro_brd/README.rst
> +Import MT940 ROMANIAN BRD Bank Statements
Put a line above

2016-06-21 07:03 UTC, pedrobaeza commented on account_bank_statement_import_mt940_ro_brd/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
Use latest template: https://raw.githubusercontent.com/OCA/maintainer-tools/master/template/module/README.rst

2016-06-21 07:04 UTC, pedrobaeza commented on account_bank_statement_import_mt940_ro_brd/__openerp__.py
> +    'version': '8.0.0.1.0',
8.0.1.0.0

2016-06-21 07:05 UTC, pedrobaeza commented on account_bank_statement_import_mt940_ro_brd/test_files/test-brd.940
> +:20:6450374100
Why not put this in the same tests folder?

2016-06-21 07:05 UTC, pedrobaeza commented on oca_dependencies.txt
> +# Add bank-statement-import repo dependency to have access to MT940 import statements modules.
You don't need to put these comments in the file.

2016-06-21 07:06 UTC, pedrobaeza commented on oca_dependencies.txt
> +bank-statement-import https://github.com/OCA/bank-statement-import 8.0
The file can be extremely simplified in this case, as the organization and branch is the same:
```
bank-statement-import
hr
partner-contact
...
```

2016-06-21 07:11 UTC, feketemihai commented on account_bank_statement_import_mt940_ro_brd/test_files/test-brd.940
> +:20:6450374100
In the https://github.com/OCA/bank-statement-import/blob/8.0/account_bank_statement_import/tests/test_import_file.py#L90 there is the path predefined to the folder "test_files" from the module path...

2016-06-21 07:12 UTC, feketemihai commented on oca_dependencies.txt
> +bank-statement-import https://github.com/OCA/bank-statement-import 8.0
@pedrobaeza  And is taken directly the 8.0 branch, even if the 9.0 is the default one?

2016-06-21 07:15 UTC, pedrobaeza commented on account_bank_statement_import_mt940_ro_brd/test_files/test-brd.940
> +:20:6450374100
Ah, OK, I made the tests independently from this: https://github.com/OCA/l10n-spain/blob/8.0/l10n_es_account_bank_statement_import_n43/tests/test_l10n_es_account_bank_statement_import_n43.py

2016-06-21 07:16 UTC, pedrobaeza commented on oca_dependencies.txt
> +bank-statement-import https://github.com/OCA/bank-statement-import 8.0
Yes, the taken branch is the same as the one you are making the changes.

2016-06-21 07:17 UTC, pedrobaeza commented
You should called the module _l10n_ro_account_bank_statement_import_mt940_brd_

2016-10-21 04:43 UTC, feketemihai commented
@pedrobaeza Can i have your lasr review here, please...

2016-10-21 06:15 UTC, pedrobaeza commented on l10n_ro_account_bank_statement_import_mt940_brd/tests/test_import_bank_statement.py
> +        )
You should make at least basic assert like the number of lines read, and some comparison between hardcoded amounts versus read amounts.

2016-10-21 06:15 UTC, pedrobaeza requested changes
You should make at least basic assert like the number of lines read, and some comparison between hardcoded amounts versus read amounts.

2016-10-21 07:42 UTC, feketemihai commented
@pedrobaeza Updated test, thanks a lot for reviewing in short time. Thanks again.

2016-10-21 08:26 UTC, pedrobaeza approved these changes

2017-10-20 09:07 UTC, merged