[FIX] create many2many report lines
OCA/l10n-romania pull request #156
Opened 2021-05-06 13:25 UTC by mcojocaru

2021-05-07 04:36 UTC, dhongu requested changes
Problema este de la Many2many. Campul trebuie sa fie One2many

2021-05-11 08:09 UTC, mcojocaru commented
am schimbat in one2many si e ok

2021-05-19 14:08 UTC, feketemihai approved these changes

2021-05-20 06:10 UTC, feketemihai commented
/ocabot merge minor

2021-05-20 06:12 UTC, merged