14.0 mrp account fix
OCA/l10n-romania pull request #409
Opened 2022-12-21 12:46 UTC by mcojocaru

2022-12-21 14:45 UTC, mcojocaru commented on l10n_ro_stock_account_mrp/models/mrp_production.py
> +MrpAccountProduction._cal_price = _cal_price
aici trebuie cu patch, altfel se apeleaza super()._cal_price, si iar ajunge in mrp_account la
m.stock_valuation_layer_ids.value
si o sa dea eroare ca pot fi 2 svl-uri

2022-12-28 22:44 UTC, mcojocaru commented on l10n_ro_stock_account_date/models/stock_move.py
>              if self.picking_id.date and self.purchase_line_id:
@feketemihai 
aici in l10n_ro_stock_account_date se face override complet fata de cea din l10n_ro_stock_account
dar daca este return, trebuie sa se execute din l10n_ro_stock_account

2022-12-30 06:34 UTC, danila12 approved these changes

2022-12-30 09:15 UTC, feketemihai requested changes

2022-12-30 09:15 UTC, feketemihai commented on l10n_ro_stock_account/tests/common.py
> +    def _make_mo(self, bom, quantity=1):
Astea treuie mutate in celalalt modul, aici nu ai instalat inca mrp..

2023-01-02 09:53 UTC, feketemihai commented
/ocabot merge minor

2023-01-02 10:20 UTC, merged