Adaugare modul ro City
OCA/l10n-romania pull request #78
Opened 2020-08-12 06:15 UTC by dhongu

2020-08-18 06:53 UTC, feketemihai commented
@dhongu Dupa cod mi se pare ca extragem foarte mult din modulul din siruta, care este deja pe versiuni anterioare, cred ca ar trebui sa ilp astram pe acela, mai ales din cauza datelor incarcate, avem aceleasi orase ca si aici, https://github.com/OCA/l10n-romania/blob/11.0/l10n_ro_config/examples/l10n_ro_siruta/res.city.csv, doar ca cine o sa aiba instalat siruta si vin din migrari, o sa-si dubleze orasele, ceea ce nu e ok, deci cred ca cel mai bine ar fi migram l10n_ro_siruta, si sa nu dublam codul in 2 module.

2020-08-18 12:45 UTC, dhongu commented
Mulul este o varianta simplificata a modului l10n_ro_siruta.

2020-08-18 17:46 UTC, dhongu commented
Modulul l10n_ro_siruta utilizeaza modelul

2020-09-02 04:34 UTC, feketemihai commented
@dhongu siruta ar trebui sa îl facem în alt pt și cu migrare sa își păstreze commiturile de pe 11 și înainte, ai procedura în issue de migrare

2020-09-02 05:47 UTC, feketemihai requested changes

2020-09-02 05:47 UTC, feketemihai commented on l10n_ro_city/models/res_country_state.py
> +# Part of Odoo. See LICENSE file for full copyright and licensing details.
Copyright si fara part of Odoo

2020-09-02 05:47 UTC, feketemihai commented on l10n_ro_city/models/__init__.py
> +# See README.rst file on addons root folder for license details
in principiu in init nu se pune copyright, ca nu e cod

2020-09-02 05:47 UTC, feketemihai commented on l10n_ro_city/README.rst
> +==========================
ar fi bine splituit fisierul si generar cu oca-gen-addon-readme, vezi exemplu https://github.com/OCA/l10n-romania/tree/13.0/l10n_ro_config/readme, si aici ai toate sectiunile: https://github.com/OCA/maintainer-tools/tree/master/template/module/readme

2020-09-02 05:47 UTC, feketemihai commented on l10n_ro_city/__init__.py
> +#
copyright

2020-09-02 05:47 UTC, feketemihai commented on l10n_ro_city/models/res_partner.py
> +#
copyright

2020-09-02 05:47 UTC, feketemihai commented on l10n_ro_city/models/res_partner.py
> +    city_id = fields.Many2one("res.city", domain="[('state_id','=',state_id)]")
poti lasa doar domeniul, este deja declarat ca si many2one si relatia

2020-09-02 05:47 UTC, feketemihai commented on l10n_ro_city/tests/__init__.py
> +# ©  2008-2020 Dorin Hongu <dhongu(@)gmail(.)com
copyright

2020-09-02 05:47 UTC, feketemihai commented on l10n_ro_city/tests/test_ro_city.py
> +#
copyright

2020-09-02 09:10 UTC, feketemihai commented
/ocabot merge

2020-09-02 09:10 UTC, feketemihai commented
/ocabot merge nobump

2020-09-02 09:11 UTC, feketemihai approved these changes

2020-09-02 09:11 UTC, merged